### ISSUE TITLE
Does not install properly

### ISSUE THREAD

**Issue by Themanwithoutaplan** [gvalkov/harstats-graphite#1]
I get a UserWarning when I try and install the package and, even though it lands in site-packages the module is not importable.

```
fuchsia:http charlieclark$ bin/pip uninstall harstats-graphite
Uninstalling harstats-graphite:
  /Users/charlieclark/Sites/http/lib/python2.7/site-packages/harstats_graphite-0.1.0-py2.7.egg-info
Proceed (y/n)? y
  Successfully uninstalled harstats-graphite
fuchsia:http charlieclark$ bin/pip install harstats-graphite
Downloading/unpacking harstats-graphite
  Downloading harstats-graphite-0.1.0.tar.gz
  Running setup.py egg_info for package harstats-graphite
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'modules'
      warnings.warn(msg)

Installing collected packages: harstats-graphite
  Running setup.py install for harstats-graphite
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'modules'
      warnings.warn(msg)

Successfully installed harstats-graphite
Cleaning up...
fuchsia:http charlieclark$ python
Python 2.7.3 (default, Oct 22 2012, 06:12:32) 
[GCC 4.2.1 Compatible Apple Clang 3.1 (tags/Apple/clang-318.0.58)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import harstats_graphite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named harstats_graphite
>>> import harstatsgraphite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named harstatsgraphite
```

I'm going to clone it and see if I can fix the issue in a fork.

**Comment by gvalkov** [comment]
No worries. The `modules` key in `setup.py` should actually be `py_modules`. Thanks for the catch.

Fixed in 3c02d5ba11081e57e414786009240a9844817d93.
